### ISSUE TITLE
Failed to compile when trying to start the project :(

### ISSUE THREAD

**Issue by InluUe4Developer** [ar-tracking/UnrealDTrackPlugin#1]
Hello, i was trying to compile this plugin for UE4.24 and 4.23 into local project plugin folder but it fails, i haven't tried the first method, not really sure if i'm doing something wrong or it's not working at the moment? i did copied sdk files to the directory.

**Comment by pz-ART** [comment]
Here some general hints, based on your sparse issue description:

- The plugin was tested (successfully) with _UE 4.23_.
- Please try the plugin with the project [UnrealDTrackSample](https://www.github.com/ar-tracking/UnrealDTrackSample) , before using it with your own projects.
- When downloading the zipped version of the plugin from Github, the contained folder has a name like _UnrealDTrackPlugin-master_. Extract this folder and rename it to _DTrackPlugin_.  Then copy this folder to _UnrealDTrackSample\Plugins\DTrackPlugin_.
- [DTrackSDK](http://github.com/ar-tracking/DTrackSDK) has to be manually compiled beforehand as a static library, no matter what installation method. The plugin build configuration expects the library named as _DTrackSDK.lib_.  After compilation copy _DTrackSDK.lib_ to the directory _DTrackPlugin\ThirdParty\DTrackSDK\Lib_.  Copy the accompanying _DTrackSDK_ headers to _DTrackPlugin\ThirdParty\DTrackSDK\Include_.

Apart from that the installation instructions for _UnrealDTrackPlugin_ and _UnrealDTrackSample_ should be followed in every detail.

If the problem persists, some more information could be helpful:  About your system, compilers, project directory structure, and what symptoms make you believe the compilation failed (e.g. as shown in _UE4Editor > Window > Developer Tools > Output Log_).

**Comment by pz-ART** [comment]
As of UnrealDTrackPlugin v0.7.2 the DTrackSDK source is now integrated into the plugin source.
