### ISSUE TITLE
How should I replace my own hand model in this plugin?

### ISSUE THREAD

**Issue by GoldenDragons** [ar-tracking/UnrealDTrackPlugin#11]
I want to use other hand models, how should I operate to run correctly?

**Comment by pz-ART** [comment]
The hand model used in [UnrealDTrackSample](https://github.com/ar-tracking/UnrealDTrackSample) is an edited version of the (UE4) mannequin, with the same mesh and bone hierarchy. What exactly is the problem you encounter when trying to use other hand models ?
