### ISSUE TITLE
Use of powerwall coordinate system

### ISSUE THREAD

**Issue by lesopi** [ar-tracking/UnrealDTrackPlugin#13]
Hi, 
Thanks for the plugin, it's very useful. 
We wanted to use the plugin with the room calibrated in powerwall mode. We found that the plugin didn't support this mode, but we were able to still use it when uncommenting the line in DTrackLiveLinkSourceSetting.h

However, we run into issues when trying to run in powerwall mode. If we consider the DTrack - Unreal alignment depicted in the readme picture (https://github.com/ar-tracking/UnrealDTrackPlugin/blob/master/Doc/images/coords-dtrack+unreal.png) and adapt coordinates to powerwall (i.e rotation +90 around X, see figure below), it seems that the matrix and the transformation in the plugin code (in DTrackSDKHandler.cpp, lines 46 and 459) don't work (at least how we expected).
We made it work the way we expected by modifying those parts, but we wanted to know if this behaviour is intentional or not.

Thanks, 
Karine

![coords-dtrackPow+unreal](https://github.com/ar-tracking/UnrealDTrackPlugin/assets/10399985/d123955e-ff02-475c-8773-24f8bd546623)

**Comment by pz-ART** [comment]
Thanks for your feedback.
Currently only the DTrack 'Normal' room calibration mode is supported, the existing code for the DTrack 'Powerwall' mode is outdated. For now the 'Normal' mode uses EDTrackCoordinateSystemType::CST_Unreal_Adapted, which is hardcoded in DTrackLiveLinkSourceSettings.h:72/73, so m_coordinate_system is not accessible via the LiveLink Source dialog.
Support for 'Powerwall' is planned for a future release.
