### ISSUE TITLE
Tracking issue in Standalone Mode

### ISSUE THREAD

**Issue by NISP2709** [ar-tracking/UnrealDTrackPlugin#2]
Issue is that using the LiveLink Plugin, it can't be activated it stays in the same frame in Standalone Game mode or using nDisplay.

If someone knows about the issue please let us know.

Regards.

**Comment by pz-ART** [comment]
If the LiveLink connection worked in the viewport as well as in PIE mode, but does not work with shipping builds, you presumably have to adapt the .uplugin file to the version of your UE4Editor. Follow the corresponding installation step in [UnrealDTrackPlugin  ("Preparation")](https://github.com/ar-tracking/UnrealDTrackPlugin#Preparation).

If the problem persists, some more information could be helpful: About your UE4Editor version, your system, compilers, and any log files in <your-project-dir>/Saved/Logs (also shown in UE4Editor > Window > Developer Tools > Output Log).
